### PR TITLE
ChangelogActivity: Use Log.e() properly

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by luk1337** [comment]
didn't even build it. Should work tho.

**Comment by luk1337** [comment]
http://developer.android.com/reference/android/util/Log.html#e(java.lang.String, java.lang.String, java.lang.Throwable)

**Comment by luca020400** [comment]
Should work :p

**Comment by bhavikrb** [comment]
Hey @luca020400 , I'm Here :dancer:

**Comment by luk1337** [comment]
@BhavikBarai who cares lol

**Pull request merged**
